server:
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/flash_lingo
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  cache:
    type: redis

app:
  jwt:
    secret-key: jwt-secret-key
    expire-length: 2592000000 #30 days
  google:
    client-id: google-client-id.apps.googleusercontent.com
    client-secret: google-client-secret
    redirect_uri: http://localhost:5173
    cloud:
      credentials: file:E:/key/google-cloud-tts.json
  pexels:
    api-key: pexels-api-key
gemini:
  api-key: gemini-api-key
  endpoint: https://generativelanguage.googleapis.com/v1/models/gemini-2.0-flash-lite:generateContent