
server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/flash_lingo}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false
  cache:
    type: redis

app:
  allowed-origins: ${ALLOWED_ORIGINS}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: ${JWT_EXPIRE_LENGTH:2592000000}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
  pexels:
    api-key: ${PEXELS_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}

# Logging configuration for production
logging:
  level:
    org.springframework.web: ${LOG_LEVEL:INFO}
    org.hibernate: WARN
    com.yourpackage: ${APP_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"